# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Business.create(name: 'Marken', password: 'marken', industry: 'Logistics', image_url: 'https://media.bizj.us/view/img/5827231/ny78064logo*750xx2392-1350-151-0.jpg', mission: '', motto: '', network: true, sell: false, collaborate: false)

Department.create(name: 'Administration', business_id: 1)
Department.create(name: 'Finance', business_id: 1)
Department.create(name: 'Human Resources', business_id: 1)
Department.create(name: 'Marketing', business_id: 1)
Department.create(name: 'Operations', business_id: 1)
Department.create(name: 'Technology', business_id: 1)

Employee.create(name: 'Sheev Palpatine', title: 'CEO', email: '', image_url: '', phone: '1111111111', department_id: 1)
Employee.create(name: 'Wilhuff Tarkin', title: 'Director', email: '', image_url: '', phone: '1111111112', department_id: 1)
Employee.create(name: 'Conan Antonio Motti', title: 'Manager', email: '', image_url: '', phone: '1111111113', department_id: 1)
Employee.create(name: 'Han Solo', title: 'CFO', email: '', image_url: '', phone: '1111111114', department_id: 2)
Employee.create(name: 'Chewbacca', title: 'Executive Director', email: '', image_url: '', phone: '1111111115', department_id: 2)
Employee.create(name: 'Leia Organa', title: 'Director', email: '', image_url: '', phone: '1111111116', department_id: 2)
Employee.create(name: 'Boba Fett', title: 'CHRO', email: '', image_url: '', phone: '1111111117', department_id: 3)
Employee.create(name: 'R2D2', title: 'Manager', email: '', image_url: '', phone: '1111111118', department_id: 3)
Employee.create(name: 'C3PO', title: 'Supervisor', email: '', image_url: '', phone: '1111111119', department_id: 3)
Employee.create(name: 'Luke Skywalker', title: 'CMO', email: '', image_url: '', phone: '1111111110', department_id: 4)
Employee.create(name: 'Yoda', title: '', email: '', image_url: '', phone: '1111111112', department_id: 4)
Employee.create(name: 'Jar Jar', title: '', email: '', image_url: '', phone: '', department_id: 4)
Employee.create(name: 'Darth Vader', title: 'COO', email: '', image_url: '', phone: '', department_id: 5)
Employee.create(name: 'Galen Marek', title: 'Vice President', email: '', image_url: '', phone: '', department_id: 5)
Employee.create(name: 'IG-88', title: 'Manager', email: '', image_url: '', phone: '', department_id: 5)
Employee.create(name: 'Thrawn', title: 'CIO', email: '', image_url: '', phone: '', department_id: 6)
Employee.create(name: 'Obi-Wan Kenobi', title: 'CTO', email: '', image_url: '', phone: '', department_id: 6)
Employee.create(name: 'Kylo Ren', title: 'Manager', email: '', image_url: '', phone: '', department_id: 6)

Business.create(name: 'Procter & Gamble', password:"12345", industry: 'Manufacturing', image_url: 'https://media.bizj.us/view/img/5827231/ny78064logo*750xx2392-1350-151-0.jpg', mission: '', motto: '', network: true, sell: false, collaborate: false)

Department.create(name: 'Administration', business_id: 2)
Department.create(name: 'Finance', business_id: 2)
Department.create(name: 'Human Resources', business_id: 2)
Department.create(name: 'Marketing', business_id: 2)
Department.create(name: 'Operations', business_id: 2)
Department.create(name: 'Technology', business_id: 2)

Employee.create(name: 'Mickey Mouse', title: 'CEO', email: '', image_url: '', phone: '', department_id: 7)
Employee.create(name: 'Donald Duck', title: '', email: '', image_url: '', phone: '', department_id: 7)
Employee.create(name: 'G.G. Goof', title: '', email: '', image_url: '', phone: '', department_id: 7)
Employee.create(name: 'Beast', title: '', email: '', image_url: '', phone: '', department_id: 8)
Employee.create(name: 'Peter Pan', title: '', email: '', image_url: '', phone: '', department_id: 8)
Employee.create(name: 'Jumba Jookiba', title: '', email: '', image_url: '', phone: '', department_id: 8)
Employee.create(name: 'Jafar', title: '', email: '', image_url: '', phone: '', department_id: 9)
Employee.create(name: 'Pinocchio', title: '', email: '', image_url: '', phone: '', department_id: 9)
Employee.create(name: 'Tigger', title: '', email: '', image_url: '', phone: '', department_id: 9)
Employee.create(name: 'Woody', title: '', email: '', image_url: '', phone: '', department_id: 10)
Employee.create(name: 'Robert Parr', title: '', email: '', image_url: '', phone: '', department_id: 10)
Employee.create(name: 'Hercules', title: '', email: '', image_url: '', phone: '', department_id: 10)
Employee.create(name: 'Mike Wazowski', title: '', email: '', image_url: '', phone: '', department_id: 11)
Employee.create(name: 'Marlin', title: '', email: '', image_url: '', phone: '', department_id: 11)
Employee.create(name: 'Tiana', title: '', email: '', image_url: '', phone: '', department_id: 11)
Employee.create(name: 'WALL-E', title: '', email: '', image_url: '', phone: '', department_id: 12)
Employee.create(name: 'Edna Mode', title: '', email: '', image_url: '', phone: '', department_id: 12)
Employee.create(name: 'Phil', title: '', email: '', image_url: '', phone: '', department_id: 12)

Business.create(name: 'XPO Logistics', password:"12345", industry: 'Logistics', image_url: 'https://media.bizj.us/view/img/5827231/ny78064logo*750xx2392-1350-151-0.jpg', mission: '', motto: '', network: true, sell: false, collaborate: false)

Department.create(name: 'Administration', business_id: 3)
Department.create(name: 'Finance', business_id: 3)
Department.create(name: 'Human Resources', business_id: 3)
Department.create(name: 'Marketing', business_id: 3)
Department.create(name: 'Operations', business_id: 3)
Department.create(name: 'Technology', business_id: 3)

Employee.create(name: 'Dumbledore', title: '', email: '', image_url: '', phone: '', department_id: 13)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 13)
Employee.create(name: 'Ron Weasley', title: '', email: '', image_url: '', phone: '', department_id: 13)
Employee.create(name: 'Cedric Diggory', title: '', email: '', image_url: '', phone: '', department_id: 14)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 14)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 14)
Employee.create(name: 'Serius Black', title: '', email: '', image_url: '', phone: '', department_id: 15)
Employee.create(name: 'Dolores Umbridge', title: '', email: '', image_url: '', phone: '', department_id: 15)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 15)
Employee.create(name: 'Dobby', title: '', email: '', image_url: '', phone: '', department_id: 16)
Employee.create(name: 'Harry Potter', title: '', email: '', image_url: '', phone: '', department_id: 16)
Employee.create(name: 'Draco Malfoy', title: '', email: '', image_url: '', phone: '', department_id: 16)
Employee.create(name: 'Rubeus Hagrid', title: '', email: '', image_url: '', phone: '', department_id: 17)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 17)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 17)
Employee.create(name: 'Duddley Dursley', title: '', email: '', image_url: '', phone: '', department_id: 18)
Employee.create(name: 'Hermione Granger', title: '', email: '', image_url: '', phone: '', department_id: 18)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 18)

Business.create(name: 'Interpublic Group', password:"12345", industry: 'Advertising', image_url: 'https://media.bizj.us/view/img/5827231/ny78064logo*750xx2392-1350-151-0.jpg', mission: '', motto: '', network: true, sell: false, collaborate: false)

Department.create(name: 'Administration', business_id: 4)
Department.create(name: 'Finance', business_id: 4)
Department.create(name: 'Human Resources', business_id: 4)
Department.create(name: 'Marketing', business_id: 4)
Department.create(name: 'Operations', business_id: 4)
Department.create(name: 'Technology', business_id: 4)

Employee.create(name: 'Eddard Stark', title: '', email: '', image_url: '', phone: '', department_id: 19)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 19)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 19)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 20)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 20)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 20)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 21)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 21)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 21)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 22)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 22)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 22)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 23)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 23)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 23)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 24)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 24)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 24)

Business.create(name: 'WilmerHale', password:"12345", industry: 'Law', image_url: 'https://media.bizj.us/view/img/5827231/ny78064logo*750xx2392-1350-151-0.jpg', mission: '', motto: '', network: true, sell: false, collaborate: false)

Department.create(name: 'Administration', business_id: 5)
Department.create(name: 'Finance', business_id: 5)
Department.create(name: 'Human Resources', business_id: 5)
Department.create(name: 'Marketing', business_id: 5)
Department.create(name: 'Operations', business_id: 5)
Department.create(name: 'Technology', business_id: 5)

Employee.create(name: 'Superman', title: 'CEO', email: '', image_url: '', phone: '', department_id: 25)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 25)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 25)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 26)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 26)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 26)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 27)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 27)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 27)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 28)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 28)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 28)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 29)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 29)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 29)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 30)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 30)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 30)