# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Business.create(name: 'Marken', industry: 'Logistics', image_url: 'https://media.bizj.us/view/img/5827231/ny78064logo*750xx2392-1350-151-0.jpg', mission: '', motto: '', network: true, sell: false, collaborate: false)

Department.create(name: 'Administration', business_id: 1)
Department.create(name: 'Finance', business_id: 1)
Department.create(name: 'Human Resources', business_id: 1)
Department.create(name: 'Marketing', business_id: 1)
Department.create(name: 'Operations', business_id: 1)
Department.create(name: 'Technology', business_id: 1)

Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 1)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 1)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 1)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 2)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 2)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 2)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 3)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 3)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 3)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 4)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 4)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 4)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 5)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 5)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 5)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 6)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 6)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 6)

Business.create(name: 'TWO', industry: 'Logistics', image_url: 'https://media.bizj.us/view/img/5827231/ny78064logo*750xx2392-1350-151-0.jpg', mission: '', motto: '', network: true, sell: false, collaborate: false)

Department.create(name: 'Administration', business_id: 1)
Department.create(name: 'Finance', business_id: 1)
Department.create(name: 'Human Resources', business_id: 1)
Department.create(name: 'Marketing', business_id: 1)
Department.create(name: 'Operations', business_id: 1)
Department.create(name: 'Technology', business_id: 1)

Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 1)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 1)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 1)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 2)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 2)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 2)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 3)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 3)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 3)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 4)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 4)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 4)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 5)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 5)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 5)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 6)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 6)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 6)

Business.create(name: 'THREE', industry: 'Logistics', image_url: 'https://media.bizj.us/view/img/5827231/ny78064logo*750xx2392-1350-151-0.jpg', mission: '', motto: '', network: true, sell: false, collaborate: false)

Department.create(name: 'Administration', business_id: 1)
Department.create(name: 'Finance', business_id: 1)
Department.create(name: 'Human Resources', business_id: 1)
Department.create(name: 'Marketing', business_id: 1)
Department.create(name: 'Operations', business_id: 1)
Department.create(name: 'Technology', business_id: 1)

Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 1)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 1)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 1)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 2)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 2)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 2)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 3)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 3)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 3)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 4)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 4)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 4)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 5)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 5)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 5)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 6)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 6)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 6)

Business.create(name: 'FOUR', industry: 'Logistics', image_url: 'https://media.bizj.us/view/img/5827231/ny78064logo*750xx2392-1350-151-0.jpg', mission: '', motto: '', network: true, sell: false, collaborate: false)

Department.create(name: 'Administration', business_id: 1)
Department.create(name: 'Finance', business_id: 1)
Department.create(name: 'Human Resources', business_id: 1)
Department.create(name: 'Marketing', business_id: 1)
Department.create(name: 'Operations', business_id: 1)
Department.create(name: 'Technology', business_id: 1)

Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 1)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 1)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 1)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 2)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 2)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 2)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 3)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 3)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 3)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 4)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 4)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 4)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 5)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 5)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 5)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 6)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 6)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 6)

Business.create(name: 'FIVE', industry: 'Logistics', image_url: 'https://media.bizj.us/view/img/5827231/ny78064logo*750xx2392-1350-151-0.jpg', mission: '', motto: '', network: true, sell: false, collaborate: false)

Department.create(name: 'Administration', business_id: 1)
Department.create(name: 'Finance', business_id: 1)
Department.create(name: 'Human Resources', business_id: 1)
Department.create(name: 'Marketing', business_id: 1)
Department.create(name: 'Operations', business_id: 1)
Department.create(name: 'Technology', business_id: 1)

Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 1)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 1)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 1)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 2)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 2)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 2)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 3)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 3)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 3)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 4)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 4)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 4)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 5)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 5)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 5)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 6)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 6)
Employee.create(name: '', title: '', email: '', image_url: '', phone: '', department_id: 6)